In [2]:
import numpy as np
import scipy.linalg

In [7]:
def lu_decomposition(matrix):
    n = len(matrix)
    lower = np.zeros((n, n) # создаем единичную матрицу
    upper = np.zeros((n, n)) # создаем матрицу из нулей
    
    lower[:, 1] = matrix[:, 1]
    upper[1, :] = matrix[1, :]/lower[1, 1]
    
    for k in range(n):
        lower[:, k] = matrix[row, k] - 
            
    return (lower, upper)

In [8]:
matrix = np.array([[1.00, 0.17, -0.25, 0.54], [0.47, 1.00, 0.67, -0.32], [-0.11, 0.35, 1.00, -0.74], [0.55, 0.43, 0.36, 1.00]])
matrix

array([[ 1.  ,  0.17, -0.25,  0.54],
       [ 0.47,  1.  ,  0.67, -0.32],
       [-0.11,  0.35,  1.  , -0.74],
       [ 0.55,  0.43,  0.36,  1.  ]])

In [9]:
lu_decomposition(matrix) # собственноручно написанная функция

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.47      ,  1.        ,  0.        ,  0.        ],
        [-0.11      ,  1.05312768,  1.        ,  0.        ],
        [ 0.55      ,  2.58926021, -0.70809042,  1.        ]]),
 array([[ 1.        ,  0.17      , -0.25      ,  0.54      ],
        [ 0.        ,  0.3501    ,  0.4775    , -0.9938    ],
        [ 0.        ,  0.        ,  0.13963153,  0.78599829],
        [ 0.        ,  0.        ,  0.        ,  3.83276465]]))

In [10]:
scipy.linalg.lu(matrix, permute_l=True) # встроенная функция

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [-0.11      ,  0.40071731,  1.        ,  0.        ],
        [ 0.47      ,  1.        ,  0.        ,  0.        ],
        [ 0.55      ,  0.36572112,  0.31889697,  1.        ]]),
 array([[ 1.        ,  0.17      , -0.25      ,  0.54      ],
        [ 0.        ,  0.9201    ,  0.7875    , -0.5738    ],
        [ 0.        ,  0.        ,  0.65693512, -0.45066841],
        [ 0.        ,  0.        ,  0.        ,  1.05656757]]))