In [1]:
import numpy as np
import scipy.linalg

In [2]:
def rearrange(matrix):
    """
    Функция создает матрицу, при умножении на которую изначальная матрица упорядочивается таким образом, чтобы максимальные элементы
    столбцов стояли на диагонали, возвращает результат умножения
    """
    n = len(matrix)
                                                                                                                                                                                          
    pivot_matrix = np.eye(n, n) # создаем единичную матрицу
    
    for index, column in enumerate(np.absolute(matrix.T)):
        row = index + np.argmax(column[index:]) # находим максимальный элемент в столбце
        if index != row:                                                                                                                                                                                                                       
            pivot_matrix[[index, row]] = pivot_matrix[[row, index]]
            
    return np.dot(pivot_matrix, matrix)

In [3]:
def lu_decomposition(matrix):
    n = len(matrix)
    lower = np.eye(n, n) # создаем единичную матрицу
    upper = np.zeros((n, n)) # создаем матрицу из нулей
    rearranged = rearrange(matrix) # упорядочиваем матрицу, поданную на входе (частичный выбор ведущего элемента)
    
    for j in range(n):
        
        # вычисляем верхнюю матрицу
        for i in range(j + 1):
            upper[i, j] = rearranged[i, j] - np.dot(upper[:i, j], lower[i, :i])
        
        # вычисляем нижнюю матрицу
        for i in range(j, n):
            lower[i, j] = (rearranged[i, j] - np.dot(upper[:i, j], lower[i, :i]))/upper[j, j]
            
    return (lower, upper)

In [4]:
matrix = np.array([[1.00, 0.17, -0.25, 0.54], [0.47, 1.00, 0.67, -0.32], [-0.11, 0.35, 1.00, -0.74], [0.55, 0.43, 0.36, 1.00]])
matrix

array([[ 1.  ,  0.17, -0.25,  0.54],
       [ 0.47,  1.  ,  0.67, -0.32],
       [-0.11,  0.35,  1.  , -0.74],
       [ 0.55,  0.43,  0.36,  1.  ]])

In [7]:
lu_decomposition(matrix) # собственноручно написанная функция

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.47      ,  1.        ,  0.        ,  0.        ],
        [-0.11      ,  0.40071731,  1.        ,  0.        ],
        [ 0.55      ,  0.36572112,  0.31889697,  1.        ]]),
 array([[ 1.        ,  0.17      , -0.25      ,  0.54      ],
        [ 0.        ,  0.9201    ,  0.7875    , -0.5738    ],
        [ 0.        ,  0.        ,  0.65693512, -0.45066841],
        [ 0.        ,  0.        ,  0.        ,  1.05656757]]))

In [8]:
scipy.linalg.lu(matrix, permute_l=True) # встроенная функция

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.47      ,  1.        ,  0.        ,  0.        ],
        [-0.11      ,  0.40071731,  1.        ,  0.        ],
        [ 0.55      ,  0.36572112,  0.31889697,  1.        ]]),
 array([[ 1.        ,  0.17      , -0.25      ,  0.54      ],
        [ 0.        ,  0.9201    ,  0.7875    , -0.5738    ],
        [ 0.        ,  0.        ,  0.65693512, -0.45066841],
        [ 0.        ,  0.        ,  0.        ,  1.05656757]]))