In [2]:
import pandas as pd
import numpy as np

In [38]:
# выгружаем данные из Excel
dataDF = pd.read_excel('usa.xls')
dataDF

Экономика США  Unnamed: 1 Unnamed: 2   Unnamed: 3
0            Год  ВВП(млн.$)   K(млн.$)  L(тыс.чел.)
1           1936       83278     234236        73426
2           1937       90884     254890        77568
3           1938       83743     217606        70460
4           1939       91530     221746        75131
5           1940      101313     228757        79694
6           1941      116415     250238        89276
7           1942      127434     266469        97056
8           1943      136274     266154       101633
9           1944      146470     269520       100124
10          1945      145052     263098        94920
11          1946      140288     252357        96671
12          1947      142022     262536       100072
13          1948      149895     285700       101304
14          1949      147122     277522        96784
15          1950      163620     307946       100352

In [39]:
dataDF = dataDF.rename(columns=dataDF.iloc[0])
dataDF = dataDF.rename(columns={'Год': 'year', 'ВВП(млн.$)': 'gdp', 'K(млн.$)': 'capital', 'L(тыс.чел.)': 'labour'})
dataDF = dataDF.iloc[1:]
dataDF

year     gdp capital  labour
1   1936   83278  234236   73426
2   1937   90884  254890   77568
3   1938   83743  217606   70460
4   1939   91530  221746   75131
5   1940  101313  228757   79694
6   1941  116415  250238   89276
7   1942  127434  266469   97056
8   1943  136274  266154  101633
9   1944  146470  269520  100124
10  1945  145052  263098   94920
11  1946  140288  252357   96671
12  1947  142022  262536  100072
13  1948  149895  285700  101304
14  1949  147122  277522   96784
15  1950  163620  307946  100352

In [65]:
gdp_data = dataDF['gdp'].to_numpy().astype(float)
capital_data = dataDF['capital'].to_numpy().astype(float)
labour_data = dataDF['labour'].to_numpy().astype(float)

In [66]:
log_gdp = np.log(gdp_data)
log_capital = np.log(capital_data)
log_labour = np.log(labour_data)

In [67]:
total_log_gdp = np.sum(log_gdp)
total_log_capital = np.sum(log_capital)
total_log_labour = np.sum(log_labour)

In [70]:
total_log_capital_log_capital = np.sum(log_capital*log_capital)
total_log_labour_log_labour = np.sum(log_labour*log_labour)
total_log_capital_log_labour = np.sum(log_capital*log_labour)
total_log_capital_log_gdp = np.sum(log_capital*log_gdp)
total_log_labour_log_gdp = np.sum(log_labour*log_gdp)

In [72]:
matrix = [[len(gdp_data), total_log_capital, total_log_labour], 
          [total_log_capital, total_log_capital_log_capital, total_log_capital_log_labour], 
          [total_log_labour, total_log_capital_log_labour, total_log_labour_log_labour]]
matrix

[[15, 186.8032839758341, 171.04056292501437],
 [186.8032839758341, 2326.4926361199764, 2130.2162554298297],
 [171.04056292501437, 2130.2162554298297, 1950.5776555960238]]

In [73]:
vector = [total_log_gdp, total_log_capital_log_gdp, total_log_labour_log_gdp]
vector

[175.5924954553971, 2187.0239325882803, 2002.6587950083972]

In [75]:
inverse = np.linalg.inv(matrix)
inverse

array([[1391.73370365, -158.90775302,   51.50523599],
       [-158.90775302,   28.7879861 ,  -17.50505258],
       [  51.50523599,  -17.50505258,   14.60134792]])

In [78]:
result = np.dot(inverse, vector)
result

array([-9.65103581,  0.35816629,  1.48182038])

In [79]:
def find_parameters(filename):
    dataDF = pd.read_excel('usa.xls')
    dataDF = dataDF.rename(columns=dataDF.iloc[0])
    dataDF = dataDF.rename(columns={'Год': 'year', 'ВВП(млн.$)': 'gdp', 'K(млн.$)': 'capital', 'L(тыс.чел.)': 'labour'})
    dataDF = dataDF.iloc[1:]
    
    gdp_data = dataDF['gdp'].to_numpy().astype(float)
    capital_data = dataDF['capital'].to_numpy().astype(float)
    labour_data = dataDF['labour'].to_numpy().astype(float)
    
    log_gdp = np.log(gdp_data)
    log_capital = np.log(capital_data)
    log_labour = np.log(labour_data)
    
    total_log_gdp = np.sum(log_gdp)
    total_log_capital = np.sum(log_capital)
    total_log_labour = np.sum(log_labour)
    
    total_log_capital_log_capital = np.sum(log_capital*log_capital)
    total_log_labour_log_labour = np.sum(log_labour*log_labour)
    total_log_capital_log_labour = np.sum(log_capital*log_labour)
    total_log_capital_log_gdp = np.sum(log_capital*log_gdp)
    total_log_labour_log_gdp = np.sum(log_labour*log_gdp)
    
    matrix = [[len(gdp_data), total_log_capital, total_log_labour], 
              [total_log_capital, total_log_capital_log_capital, total_log_capital_log_labour], 
              [total_log_labour, total_log_capital_log_labour, total_log_labour_log_labour]]  
    vector = [total_log_gdp, total_log_capital_log_gdp, total_log_labour_log_gdp]
    inverse = np.linalg.inv(matrix)
    
    return np.dot(inverse, vector)

In [80]:
find_parameters('usa.xls')

array([-9.65103581,  0.35816629,  1.48182038])